### GET: Get all persons
GET {{host}}/api/person
Accept: application/json

### POST: Add a new person
POST {{host}}/api/person
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "dob": "1990-01-01",
  "roomNo": "101",
  "isWorker": true,
  "password": "password123"
}

### GET: Get a person by ID
GET {{host}}/api/person/1
Accept: application/json

### PUT: Update a person
PUT {{host}}/api/person/1
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "dob": "1990-01-01",
  "roomNo": "102",
  "isWorker": false,
  "password": "newpassword123"
}

### DELETE: Delete a person
DELETE {{host}}/api/person/1
Accept: application/json


### Authentication


### POST: Login as a worker
POST {{host}}/api/person/login
Content-Type: application/json

{
  "firstName": "Anna",
  "lastName": "Müller",
  "password": "$2a$10$examplehashedpassword1"
}

### POST: Login as a senior (should fail)
POST {{host}}/api/person/login
Content-Type: application/json

{
  "firstName": "Franz",
  "lastName": "Huber",
  "password": "newpassword123"
}